### ISSUE TITLE
License for Code?

### ISSUE THREAD

**Issue by BBCXC** [tayloryoung6396/0373CELE#2]
Having your code on the internet, publicly available for everyone else in the course to use isn't very defensible IMO from a collusion standpoint, regarding UoN's academic integrity policy i would argue.

Can we at least clarify the license of the code here =)

**Comment by tayloryoung6396** [comment]
The license has now been added to the repo. 
I do agree open code might be somewhat against the UoN academic integrity policy however, if they wish to provide a degree following industry practice then using a repo should be encouraged.
